try improved job summary

diff --git a/.github/workflows/connector-tests.yml b/.github/workflows/connector-tests.yml
--- a/.github/workflows/connector-tests.yml
+++ b/.github/workflows/connector-tests.yml
@@ -119,9 +119,24 @@ jobs:
           test \
           --fail-fast \
           --skip-step qa_checks
+          # save job output json file as ci step output
+          json_output_file=$(find airbyte/airbyte-ci/connectors/pipelines/pipeline_reports -name 'output.json' -print -quit)
+          job_output=$(cat $json_output_file)
+          echo "job_output=$job_output" >> $GITHUB_OUTPUT
+          succes=$(echo $job_output | jq -r '.success')
+          failed_jobs=$(echo $job_output | jq -r '.failed_steps')
+          echo "succes=${succes}\nfailed_jobs=${failed_jobs}" >> $GITHUB_OUTPUT
+          echo "## Job Output for ${{matrix.connector}}" >> $GITHUB_STEP_SUMMARY
+          echo "- Success: ${success}" >> $GITHUB_STEP_SUMMARY
+          echo "- Failed Jobs: ${failed_jobs}" >> $GITHUB_STEP_SUMMARY
+          if [ "$succes" != "true" ]; then
+            echo "status=failed" >> $GITHUB_OUTPUT
+            exit 1
+          fi
 
       # Upload the job output to the artifacts
       - name: Upload Job Output
+        id: upload_job_output
         if: always()
         uses: actions/upload-artifact@v4
         with:
@@ -131,5 +146,4 @@ jobs:
       - name: Add Notice to Job Summary
         if: always()
         run: |
-          echo "## Job Output for ${{matrix.connector}}" >> $GITHUB_STEP_SUMMARY
-          echo "[Download Job Output](./artifacts/${{matrix.connector}}-job-output)" >> $GITHUB_STEP_SUMMARY
+          echo "\n[Download Job Output](${{steps.upload_job_output.outputs.artifact-url}})" >> $GITHUB_STEP_SUMMARY
